[package]
name = "moonstone"
version = "0.0.1"
description = "MoonStone E2EE IM"
authors = ["苏向夜 <fu050409@163.com>"]
license = "Apache-2.0"
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1", features = [ "notification-all", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
oblivion = { path = "oblivion" }
thiserror = "1"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
